<testResult cycle="001" cvus="000" thread="001" suite="Distlock" name="test_distlock"  time="1347651478.19" result="Error" steps="0" duration="0.0122539997101" connection_duration="0.0" requests="0" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback='Traceback (most recent call last):&#10;   File "/usr/local/lib/python2.7/dist-packages/funkload-1.17.0-py2.7.egg/funkload/FunkLoadTestCase.py", line 975, in __call__&#10;    testMethod()&#10;   File "/home/ben/dev/tickets/distlock/distlock/ftest/funkload/test_Distlock.py", line 68, in test_distlock&#10;    ws.connect()&#10;   File "/usr/local/lib/python2.7/dist-packages/ws4py-0.2.3-py2.7.egg/ws4py/client/__init__.py", line 42, in connect&#10;    self.sock.connect((host, int(port)))&#10;   File "/usr/lib/python2.7/socket.py", line 224, in meth&#10;    return getattr(self._sock,name)(*args)&#10; error: [Errno 111] Connection refused&#10;' />
